export enum PropertyType {
	APARTMENT = 'APARTMENT',
	DORMITORY = 'DORMITORY',
	SINGLE_ROOM = 'SINGLE_ROOM',
	STUDIO = 'STUDIO',
	HOUSE = 'HOUSE',
}

export enum PropertyAmenities {
	ELEVATOR = 'ELEVATOR',
	INTERNET = 'INTERNET',
	PARKING = 'PARKING',
	WASHING_MACHINE = 'WASHING_MACHINE',
	DISHWASHER = 'DISHWASHER',
	AIR_CONDITIONER = 'AIR_CONDITIONER',
	VACUUM_CLEANER = 'VACUUM_CLEANER',
	HEAT_PUMP = 'HEAT_PUMP',
	FURNITURE = 'FURNITURE',
	TV = 'TV',
}

export enum StayDuration {
	MONTHLY = 'MONTHLY',
	HALF_YEATR = 'HALF_YEATR',
	ANNUAL = 'ANNUAL',
}

export enum PropertyStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
}

export enum PropertyUtilityBills {
	GAS = 'GAS',
	WATER = 'WATER',
	ELECTRICITY = 'ELECTRICITY',
	INTERNET = 'INTERNET',
}
